# -*- coding: utf-8 -*-
"""JobsPipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ToJ_gvKzNpPvVWuiksBW6O-Eb0ytk8a
"""

# Install dependencies
!pip install outscraper google-generativeai html2text

import os
import sqlite3
import hashlib
import requests
import json
import html2text
from outscraper import ApiClient
import google.generativeai as genai

# --- CONFIGURATION ---
# Set these as environment variables or Colab secrets — never hardcode keys here.
OUTSCRAPER_API_KEY    = os.environ.get('OUTSCRAPER_API_KEY', '')
CLOUDFLARE_API_TOKEN  = os.environ.get('CF_API_TOKEN', '')
CLOUDFLARE_ACCOUNT_ID = os.environ.get('CF_ACCOUNT_ID', '')
GOOGLE_API_KEY        = os.environ.get('GOOGLE_API_KEY', '')

# --- DATABASE INITIALIZATION ---
def init_db():
    conn = sqlite3.connect('skagit_jobs.db')
    cursor = conn.cursor()
    # Create the businesses table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS businesses (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT,
            city TEXT,
            homepage_url TEXT,
            careers_url TEXT,
            last_hash TEXT,
            is_active INTEGER DEFAULT 1
        )
    ''')
    # Create the jobs table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS job_postings (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER,
            job_title TEXT,
            salary TEXT,
            apply_link TEXT,
            detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ''')
    conn.commit()
    conn.close()
    print("🏠 Database and tables initialized.")

init_db()

# Initialize AI
genai.configure(api_key=GOOGLE_API_KEY)
model = genai.GenerativeModel('gemini-1.5-flash')
out_client = ApiClient(OUTSCRAPER_API_KEY)

print("✅ Setup Complete")

def seed_businesses(queries):
    conn = sqlite3.connect('skagit_jobs.db')
    cursor = conn.cursor()

    for query in queries:
        print(f"🔍 Searching Outscraper for: {query}...")
        results = out_client.google_maps_search(query, limit=20, language='en')

        # Outscraper returns a list of results (one per query)
        # We grab the first list of places
        places = results[0] if results else []

        for place in places:
            name = place.get('name')
            # FIX: Outscraper uses 'website', your old code used 'site'
            site = place.get('website')
            city = place.get('city')

            if site:
                print(f"  ✅ Saving: {name} ({site})")
                cursor.execute('''
                    INSERT OR IGNORE INTO businesses (name, city, homepage_url)
                    VALUES (?, ?, ?)
                ''', (name, city, site))
            else:
                print(f"  ⚠️ Skipping {name}: No website found.")

    conn.commit()
    conn.close()
    print("\n🏁 Discovery Phase Complete. Run the 'Scout' cell next.")

# Example Seed Run
seed_businesses(['Manufacturing in Sedro-Woolley, WA', 'Manufacturing in Mount Vernon, WA'])

def scout_careers_pages():
    conn = sqlite3.connect('skagit_jobs.db')
    cursor = conn.cursor()
    cursor.execute('SELECT id, homepage_url FROM businesses WHERE careers_url IS NULL')
    rows = cursor.fetchall()

    keywords = ['jobs', 'career', 'hiring', 'employment', 'work']

    for row_id, url in rows:
        try:
            print(f"Scouting: {url}")
            # Simple link sniffing (In Worker, use Browser Rendering)
            response = requests.get(url, timeout=10)
            target_url = url # Default

            # Logic: If 'careers' exists in any <a> tag, use that.
            # (Simulated for this script)
            cursor.execute('UPDATE businesses SET careers_url = ? WHERE id = ?', (target_url, row_id))
        except:
            continue

    conn.commit()
    conn.close()
    print("✅ Scouting Phase Complete")

scout_careers_pages()

def run_delta_crawler():
    conn = sqlite3.connect('skagit_jobs.db')
    cursor = conn.cursor()
    cursor.execute('SELECT id, careers_url, last_hash FROM businesses')
    rows = cursor.fetchall()

    h = html2text.HTML2Text()
    h.ignore_links = False

    for b_id, url, old_hash in rows:
        try:
            print(f"Crawling: {url}")
            # In Production: Call Cloudflare Browser Rendering API
            # For Colab: Standard request
            resp = requests.get(url, timeout=15)
            markdown_content = h.handle(resp.text)

            new_hash = hashlib.sha256(markdown_content.encode()).hexdigest()

            if new_hash != old_hash:
                print(f" ✨ Change detected for Business ID {b_id}!")
                # Simulate R2 Upload
                with open(f"change_{b_id}.md", "w") as f:
                    f.write(markdown_content)

                cursor.execute('UPDATE businesses SET last_hash = ? WHERE id = ?', (new_hash, b_id))
                # Trigger extraction
                extract_jobs_from_markdown(b_id, markdown_content)
        except Exception as e:
            print(f"Error crawling {url}: {e}")

    conn.commit()
    conn.close()

def extract_jobs_from_markdown(business_id, markdown_text):
    # This tells Gemini exactly how to format the data
    prompt = f"""
    Extract all active job postings from the following markdown text.
    Return a list of objects with "job_title", "salary", and "apply_link".

    TEXT:
    {markdown_text[:5000]}
    """

    # Use 'response_mime_type' to force clean JSON output
    response = model.generate_content(
        prompt,
        generation_config={"response_mime_type": "application/json"}
    )

    try:
        # No more .replace() needed!
        jobs = json.loads(response.text)

        print(f"✅ Found {len(jobs)} jobs for Business {business_id}")
        for job in jobs:
            print(f" - {job.get('job_title', 'N/A')}")

    except Exception as e:
        print(f"❌ Extraction error: {e}")

# This triggers the crawl, hash check, and Gemini extraction
run_delta_crawler()

import pandas as pd

# Connect and view the businesses we've found so far
conn = sqlite3.connect('/content/skagit_jobs.db')
df_businesses = pd.read_sql_query("SELECT * FROM businesses", conn)
conn.close()

# Show the table in a nice clean format
df_businesses