from __future__ import annotations

import os
import re
from collections.abc import Iterator, Mapping
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

try:
    import psycopg
except ImportError as exc:  # pragma: no cover - exercised before app startup
    raise RuntimeError("psycopg is required. Install crawler requirements with `pip install -r requirements.txt`.") from exc


load_dotenv(Path(__file__).with_name(".env"))


class IntegrityError(Exception):
    pass


IntegrityError = psycopg.IntegrityError


def database_url() -> str:
    url = os.environ.get("DATABASE_PUBLIC_URL") or os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_PUBLIC_URL or DATABASE_URL is required in crawler/.env.")
    return url


class Row(Mapping[str, Any]):
    def __init__(self, columns: list[str], values: tuple[Any, ...]):
        self._columns = columns
        self._values = values
        self._index = {column: index for index, column in enumerate(columns)}

    def __getitem__(self, key: str | int) -> Any:
        if isinstance(key, int):
            return self._values[key]
        return self._values[self._index[key]]

    def __iter__(self) -> Iterator[str]:
        return iter(self._columns)

    def __len__(self) -> int:
        return len(self._columns)

    def keys(self) -> list[str]:
        return list(self._columns)

    def values(self) -> tuple[Any, ...]:
        return self._values


class Result:
    def __init__(self, cursor: Any | None = None, rows: list[Row] | None = None, rowcount: int = -1):
        self._cursor = cursor
        self._rows = rows
        self._rowcount = rowcount
        self.lastrowid: int | None = None

    @property
    def rowcount(self) -> int:
        if self._cursor is not None:
            return self._cursor.rowcount
        return self._rowcount

    def _columns(self) -> list[str]:
        if self._cursor is None or self._cursor.description is None:
            return []
        return [column.name for column in self._cursor.description]

    def fetchone(self) -> Row | None:
        if self._rows is not None:
            return self._rows.pop(0) if self._rows else None
        if self._cursor is None:
            return None
        row = self._cursor.fetchone()
        return Row(self._columns(), row) if row is not None else None

    def fetchall(self) -> list[Row]:
        if self._rows is not None:
            rows = self._rows
            self._rows = []
            return rows
        if self._cursor is None:
            return []
        columns = self._columns()
        return [Row(columns, row) for row in self._cursor.fetchall()]

    def __iter__(self) -> Iterator[Row]:
        while True:
            row = self.fetchone()
            if row is None:
                break
            yield row


class Connection:
    def __init__(self) -> None:
        self._conn = psycopg.connect(database_url())
        self.row_factory = None

    def __enter__(self) -> "Connection":
        return self

    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        if exc_type is None:
            self._conn.commit()
        else:
            self._conn.rollback()
        self._conn.close()

    def execute(self, sql: str, params: Any = None) -> Result:
        translated = translate_sql(sql)
        if translated is None:
            return Result(rows=[])
        pragma_rows = table_info_rows(self._conn, translated)
        if pragma_rows is not None:
            return Result(rows=pragma_rows, rowcount=len(pragma_rows))
        cursor = self._conn.execute(translated, params)
        return Result(cursor=cursor)

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()


def connect(_: Path | None = None, timeout: int | None = None) -> Connection:
    return Connection()


def translate_sql(sql: str) -> str | None:
    stripped = sql.strip()
    upper = stripped.upper()
    if upper.startswith("PRAGMA BUSY_TIMEOUT") or upper.startswith("PRAGMA JOURNAL_MODE"):
        return None
    if upper == "BEGIN IMMEDIATE":
        return "BEGIN"

    sql = re.sub(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql, flags=re.I)
    sql = re.sub(r"INSERT\s+OR\s+IGNORE\s+INTO\s+(.+?)\s+VALUES\s*(\(.+?\))", r"INSERT INTO \1 VALUES \2 ON CONFLICT DO NOTHING", sql, flags=re.I | re.S)
    sql = re.sub(r"([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)?)\s+COLLATE\s+NOCASE", r"LOWER(\1)", sql, flags=re.I)
    return replace_qmark_placeholders(sql)


def replace_qmark_placeholders(sql: str) -> str:
    output: list[str] = []
    in_single = False
    in_double = False
    i = 0
    while i < len(sql):
        char = sql[i]
        if char == "'" and not in_double:
            output.append(char)
            if i + 1 < len(sql) and sql[i + 1] == "'":
                output.append(sql[i + 1])
                i += 2
                continue
            in_single = not in_single
        elif char == '"' and not in_single:
            output.append(char)
            in_double = not in_double
        elif char == "?" and not in_single and not in_double:
            output.append("%s")
        else:
            output.append(char)
        i += 1
    return "".join(output)


def table_info_rows(conn: Any, sql: str) -> list[Row] | None:
    match = re.fullmatch(r"\s*PRAGMA\s+table_info\(([^)]+)\)\s*", sql, flags=re.I)
    if not match:
        return None
    table = match.group(1).strip("\"'")
    rows = conn.execute(
        """
        SELECT column_name, data_type, is_nullable, column_default
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = %s
        ORDER BY ordinal_position
        """,
        (table,),
    ).fetchall()
    columns = ["cid", "name", "type", "notnull", "dflt_value", "pk"]
    return [
        Row(columns, (index, row[0], row[1], 1 if row[2] == "NO" else 0, row[3], 1 if row[0] == "id" else 0))
        for index, row in enumerate(rows)
    ]
